Repository pytroll/trollflow2, pull requests merged in 2019-04, with the labels that each got.

#27 Add overviews to output images
  examples/pl.yaml
  trollflow2/__init__.py
  trollflow2/launcher.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#25 Add a possibility to send emails about crashes
  examples/pl.yaml
  trollflow2/__init__.py
  trollflow2/launcher.py
  trollflow2/tests/test_launcher.py
Labels: enhancement

#6 Add a docker example
  examples/docker/README
  examples/docker/build_dir/Dockerfile_dev
  examples/docker/build_dir/Dockerfile_stable
  examples/docker/build_dir/entrypoint.sh
  examples/docker/build_dir/requirements_dev.txt
  examples/docker/build_dir/requirements_stable.txt
  examples/docker/config_ears_avhrr/README
  examples/docker/config_ears_avhrr/gatherer_ears_avhrr.ini
  examples/docker/config_ears_avhrr/supervisord.conf
  examples/docker/config_ears_avhrr/trollflow2_ears_avhrr.yaml
  examples/docker/config_ears_avhrr/trollstalker.ini
  examples/docker/config_ears_avhrr/trollstalker_logging.ini
  examples/docker/config_ears_viirs/README
  examples/docker/config_ears_viirs/gatherer_ears_viirs.ini
  examples/docker/config_ears_viirs/segment_gatherer_ears_viirs.ini
  examples/docker/config_ears_viirs/supervisord.conf
  examples/docker/config_ears_viirs/trollflow2_ears_viirs.yaml
  examples/docker/config_ears_viirs/trollstalker.ini
  examples/docker/config_ears_viirs/trollstalker_logging.ini
  examples/docker/config_seviri_hrit/README
  examples/docker/config_seviri_hrit/segment_gatherer.yaml
  examples/docker/config_seviri_hrit/supervisord.conf
  examples/docker/config_seviri_hrit/trollflow2_seviri_hrit.yaml
  examples/docker/config_seviri_hrit/trollstalker.ini
  examples/docker/config_seviri_hrit/trollstalker_logging.ini
  examples/docker/input/README
  examples/docker/logs/README
  examples/docker/output/README
Labels: enhancement

#30 Use only one sensor for coverage calculations
  trollflow2/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: bug, enhancement

#32 Feature sunlight coverage
  doc/Makefile
  doc/make.bat
  doc/source/conf.py
  doc/source/index.rst
  examples/pl.yaml
  setup.py
  trollflow2/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#33 Fix hanging publisher
  trollflow2/__init__.py
  trollflow2/launcher.py
  trollflow2/tests/test_launcher.py
  trollflow2/tests/test_trollflow2.py
Labels: bug

#34 Add debuginfo area coverage
  trollflow2/__init__.py
Labels: enhancement
