Repository pytroll/trollflow2, pull requests merged in 2019-03, with the labels that each got.

#15 Fix plist_iter to provide the area and product keys too
  trollflow2/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: bug

#16 Make it possible to delay composite creation
  examples/pl.yaml
  trollflow2/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#17 Allow formats to be specified at any level
  trollflow2/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#20 Handling nicer the situation where the scene cannot be created when th…
  trollflow2/__init__.py
  trollflow2/launcher.py
Labels: bug, enhancement

#22 Make publish topic composable
  README.md
  setup.py
  trollflow2/__init__.py
  trollflow2/tests/test_launcher.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#24 Check `collection_area_id` in the input metadata
  examples/pl.yaml
  trollflow2/__init__.py
  trollflow2/launcher.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#23 Add a possibility to define subscribe topics in config file
  bin/satpy_launcher.py
  examples/pl.yaml
  trollflow2/launcher.py
  trollflow2/tests/test_launcher.py
Labels: enhancement
