Repository pytroll/trollflow2, pull requests merged in 2019-06, with the labels that each got.

#38 Handle gracefully the situation when a dataset is not loaded
  trollflow2/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: bug

#39 Refactor trollflow2 to put plugins in their own file
  doc/source/index.rst
  examples/docker/config_ears_avhrr/trollflow2_ears_avhrr.yaml
  examples/docker/config_ears_viirs/trollflow2_ears_viirs.yaml
  examples/docker/config_seviri_hrit/trollflow2_seviri_hrit.yaml
  examples/pl.yaml
  trollflow2/__init__.py
  trollflow2/dict_tools.py
  trollflow2/launcher.py
  trollflow2/plugins/__init__.py
  trollflow2/tests/__init__.py
  trollflow2/tests/test_dict_tools.py
  trollflow2/tests/test_launcher.py
  trollflow2/tests/test_trollflow2.py
  trollflow2/tests/utils.py
Labels: API change, enhancement

#40 Add the areas level
  doc/source/conf.py
  doc/source/index.rst
  examples/docker/config_ears_avhrr/trollflow2_ears_avhrr.yaml
  examples/docker/config_ears_viirs/trollflow2_ears_viirs.yaml
  examples/docker/config_seviri_hrit/trollflow2_seviri_hrit.yaml
  examples/pl.yaml
  setup.py
  trollflow2/dict_tools.py
  trollflow2/launcher.py
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_dict_tools.py
  trollflow2/tests/test_launcher.py
  trollflow2/tests/test_trollflow2.py
Labels: API change, WIP, enhancement
