Repository pytroll/trollflow2, pull requests merged in 2019-11, with the labels that each got.

#57 Add the possibility to add extra metadata to the published messages
  examples/pl.yaml
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#59 Add "nameserver" and "addresses" command-line options
  bin/satpy_launcher.py
  examples/pl.yaml
  trollflow2/launcher.py
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_launcher.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#62 Check if the composites are actually produced when the trollflow2 process is over
  bin/satpy_launcher.py
  trollflow2/launcher.py
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_launcher.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#61 Ensure composites are generated for scenes without resampling
  examples/pl.yaml
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: bug, enhancement

#53 Add max daylight coverage feature
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#63 Fix publisher stopping after first processed area
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: bug

#65 Stop the workers when the process is done
  doc/source/index.rst
  trollflow2/launcher.py
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_launcher.py
  trollflow2/tests/test_trollflow2.py
Labels: bug, enhancement

#66 Fix formats dictionary being the same object
  trollflow2/launcher.py
  trollflow2/tests/test_launcher.py
Labels: bug

#67 Use area definition names to check sunlight coverage
  examples/pl.yaml
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement
