Repository pytroll/trollflow2, pull requests merged in 2022-03, with the labels that each got.

#139 Fix warning issued when multiple sensors are provided
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#140 Fix sunlight coverage check to return 100% when the data is fully lit
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: bug

#138 Make it possible to do eager saving
  doc/source/index.rst
  examples/pl.yaml
  trollflow2/plugins/__init__.py
  trollflow2/tests/test_trollflow2.py
Labels: enhancement

#141 Add a .readthedocs.yaml file
  .readthedocs.yaml
Labels: documentation

#142 Add os in the .readthedocs.yaml file
  .readthedocs.yaml
Labels: documentation

#143 Add installation method in the .readthedocs.yaml file
  .readthedocs.yaml
Labels: documentation
